class BloodDonor {
  int? nguoiHienMauId;
  String? hoVaTen;
  String? hoVaTenNoDiacritics;
  DateTime? ngaySinh;
  String? namSinh;
  String? cmnd;
  bool? gioiTinh;
  String? maXa;
  String? tenXa;
  String? maHuyen;
  String? tenHuyen;
  String? maTinh;
  String? tenTinh;
  String? diaChiLienLac;
  String? ngheNghiep;
  String? email;
  String? soDT;
  String? maNhomMau;
  String? tenNhomMau;
  String? ghiChu;
  int? soLanHienMau;
  DateTime? updatedTime;
  String? updatedBy;

  BloodDonor(
      {this.nguoiHienMauId,
      this.hoVaTen,
      this.hoVaTenNoDiacritics,
      this.ngaySinh,
      this.namSinh,
      this.cmnd,
      this.gioiTinh,
      this.maXa,
      this.tenXa,
      this.maHuyen,
      this.tenHuyen,
      this.maTinh,
      this.tenTinh,
      this.diaChiLienLac,
      this.ngheNghiep,
      this.email,
      this.soDT,
      this.maNhomMau,
      this.tenNhomMau,
      this.ghiChu,
      this.soLanHienMau,
      this.updatedTime,
      this.updatedBy});

  BloodDonor.fromJson(Map<String, dynamic> json) {
    nguoiHienMauId = json['nguoiHienMauId'];
    hoVaTen = json['hoVaTen'];
    hoVaTenNoDiacritics = json['hoVaTenNoDiacritics'];
    ngaySinh =
        json['ngaySinh'] != null ? DateTime.parse(json['ngaySinh']) : null;
    namSinh = json['namSinh']?.toString();
    cmnd = json['cmnd'];
    gioiTinh = json['gioiTinh'];
    maXa = json['maXa'];
    tenXa = json['tenXa'];
    maHuyen = json['maHuyen'];
    tenHuyen = json['tenHuyen'];
    maTinh = json['maTinh'];
    tenTinh = json['tenTinh'];
    diaChiLienLac = json['diaChiLienLac'];
    ngheNghiep = json['ngheNghiep'];
    email = json['email'];
    soDT = json['soDT'];
    maNhomMau = json['maNhomMau'];
    tenNhomMau = json['tenNhomMau'];
    ghiChu = json['ghiChu'];
    soLanHienMau = json['soLanHienMau'];
    updatedTime = json['updatedTime'] != null
        ? DateTime.parse(json['updatedTime'])
        : null;
    updatedBy = json['updatedBy'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['nguoiHienMauId'] = nguoiHienMauId;
    data['hoVaTen'] = hoVaTen;
    data['hoVaTenNoDiacritics'] = hoVaTenNoDiacritics;
    data['ngaySinh'] = ngaySinh?.toIso8601String();
    data['namSinh'] = namSinh;
    data['cmnd'] = cmnd;
    data['gioiTinh'] = gioiTinh;
    data['maXa'] = maXa;
    data['tenXa'] = tenXa;
    data['maHuyen'] = maHuyen;
    data['tenHuyen'] = tenHuyen;
    data['maTinh'] = maTinh;
    data['tenTinh'] = tenTinh;
    data['diaChiLienLac'] = diaChiLienLac;
    data['ngheNghiep'] = ngheNghiep;
    data['email'] = email;
    data['soDT'] = soDT;
    data['maNhomMau'] = maNhomMau;
    data['tenNhomMau'] = tenNhomMau;
    data['ghiChu'] = ghiChu;
    data['soLanHienMau'] = soLanHienMau;
    data['updatedTime'] = updatedTime?.toIso8601String();
    data['updatedBy'] = updatedBy;
    return data;
  }
}

class Autogenerated {
  int? nguoiHienMauId;
  String? hoVaTen;
  String? hoVaTenNoDiacritics;
  DateTime? ngaySinh;
  String? namSinh;
  String? cmnd;
  bool? gioiTinh;
  String? maXa;
  String? tenXa;
  String? maHuyen;
  String? tenHuyen;
  String? maTinh;
  String? tenTinh;
  String? diaChiLienLac;
  String? ngheNghiep;
  String? email;
  String? soDT;
  String? maNhomMau;
  String? tenNhomMau;
  String? ghiChu;
  int? soLanHienMau;
  String? updatedTime;
  String? updatedBy;

  Autogenerated(
      {this.nguoiHienMauId,
      this.hoVaTen,
      this.hoVaTenNoDiacritics,
      this.ngaySinh,
      this.namSinh,
      this.cmnd,
      this.gioiTinh,
      this.maXa,
      this.tenXa,
      this.maHuyen,
      this.tenHuyen,
      this.maTinh,
      this.tenTinh,
      this.diaChiLienLac,
      this.ngheNghiep,
      this.email,
      this.soDT,
      this.maNhomMau,
      this.tenNhomMau,
      this.ghiChu,
      this.soLanHienMau,
      this.updatedTime,
      this.updatedBy});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    nguoiHienMauId = json['nguoiHienMauId'];
    hoVaTen = json['hoVaTen'];
    hoVaTenNoDiacritics = json['hoVaTenNoDiacritics'];
    ngaySinh = json['ngaySinh'];
    namSinh = json['namSinh'];
    cmnd = json['cmnd'];
    gioiTinh = json['gioiTinh'];
    maXa = json['maXa'];
    tenXa = json['tenXa'];
    maHuyen = json['maHuyen'];
    tenHuyen = json['tenHuyen'];
    maTinh = json['maTinh'];
    tenTinh = json['tenTinh'];
    diaChiLienLac = json['diaChiLienLac'];
    ngheNghiep = json['ngheNghiep'];
    email = json['email'];
    soDT = json['soDT'];
    maNhomMau = json['maNhomMau'];
    tenNhomMau = json['tenNhomMau'];
    ghiChu = json['ghiChu'];
    soLanHienMau = json['soLanHienMau'];
    updatedTime = json['updatedTime'];
    updatedBy = json['updatedBy'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['nguoiHienMauId'] = nguoiHienMauId;
    data['hoVaTen'] = hoVaTen;
    data['hoVaTenNoDiacritics'] = hoVaTenNoDiacritics;
    data['ngaySinh'] = ngaySinh;
    data['namSinh'] = namSinh;
    data['cmnd'] = cmnd;
    data['gioiTinh'] = gioiTinh;
    data['maXa'] = maXa;
    data['tenXa'] = tenXa;
    data['maHuyen'] = maHuyen;
    data['tenHuyen'] = tenHuyen;
    data['maTinh'] = maTinh;
    data['tenTinh'] = tenTinh;
    data['diaChiLienLac'] = diaChiLienLac;
    data['ngheNghiep'] = ngheNghiep;
    data['email'] = email;
    data['soDT'] = soDT;
    data['maNhomMau'] = maNhomMau;
    data['tenNhomMau'] = tenNhomMau;
    data['ghiChu'] = ghiChu;
    data['soLanHienMau'] = soLanHienMau;
    data['updatedTime'] = updatedTime;
    data['updatedBy'] = updatedBy;
    return data;
  }
}
