//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB.CR.Repositories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BzLogicResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BzLogicResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BB.CR.Repositories.BzLogicResource", typeof(BzLogicResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã tồn tại.
        /// </summary>
        internal static string AccountExisted {
            get {
                return ResourceManager.GetString("AccountExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tạo được tài khoản này.
        ///Vui lòng liên hệ Trung tâm để được hổ trợ..
        /// </summary>
        internal static string AccountUnRegisterAdmin {
            get {
                return ResourceManager.GetString("AccountUnRegisterAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại (chưa đăng ký).
        /// </summary>
        internal static string AccountUnRegistered {
            get {
                return ResourceManager.GetString("AccountUnRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã yêu cầu mật khẩu cho CCCD &apos;{0}&apos; vào ngày &apos;{1}&apos; rồi.
        /// </summary>
        internal static string CapMatKhauTonTai {
            get {
                return ResourceManager.GetString("CapMatKhauTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đăng ký lịch hiến máu khác trong ngày. Vui lòng huỷ đăng ký để đăng ký lại..
        /// </summary>
        internal static string DaDangKyHienMau {
            get {
                return ResourceManager.GetString("DaDangKyHienMau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa đủ số ngày quy định ({0} ngày) để hiến máu. 
        ///Lần hiến máu gần nhất của bạn là {1}.
        /// </summary>
        internal static string DaysNotEnough {
            get {
                return ResourceManager.GetString("DaysNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang đăng nhập trên thiết bị khác.
        ///Vui lòng sử dụng đúng thiết bị đã đăng ký tài khoản..
        /// </summary>
        internal static string DeviceOtherCheckOTP {
            get {
                return ResourceManager.GetString("DeviceOtherCheckOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu người hiến máu đang trùng CCCD/CMND.
        ///Vui lòng liên hệ trung tâm để được hỗ trợ theo {0}..
        /// </summary>
        internal static string DMNguoiHienMauDuplicateCMND {
            get {
                return ResourceManager.GetString("DMNguoiHienMauDuplicateCMND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hành chính người hiến máu đã tồn tại
        ///Họ và tên: {0}
        ///CMND: {1}
        ///Số điện thoại: {2}.
        /// </summary>
        internal static string DMNguoiHienMauExists {
            get {
                return ResourceManager.GetString("DMNguoiHienMauExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin người hiến máu với CMND {0}
        ///Vui lòng nhập đầy đủ thông tin để thực hiện tiếp tục..
        /// </summary>
        internal static string DMNguoiHienMauNotFoundByIdCard {
            get {
                return ResourceManager.GetString("DMNguoiHienMauNotFoundByIdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng thông tin, liên hệ trung tâm truyền máu.
        /// </summary>
        internal static string ExistsInfoPeopleCategory {
            get {
                return ResourceManager.GetString("ExistsInfoPeopleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đã được sử dụng trên thiết bị khác.
        ///Vui lòng đăng xuất khỏi thiết bị hoặc liên hệ trung tâm truyền máu..
        /// </summary>
        internal static string InfoUseOtherDevice {
            get {
                return ResourceManager.GetString("InfoUseOtherDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đồng nhất.
        ///Vui lòng kiểm tra lại..
        /// </summary>
        internal static string NewPasswordConfirmPasswordNotSame {
            get {
                return ResourceManager.GetString("NewPasswordConfirmPasswordNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã nhập sai mật khẩu cũ.
        ///Vui lòng kiểm tra lại..
        /// </summary>
        internal static string OldPasswordWrong {
            get {
                return ResourceManager.GetString("OldPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã hết hạn.
        ///Vui lòng nhấn gửi lại để cấp OTP mới..
        /// </summary>
        internal static string OTPExpiredTime {
            get {
                return ResourceManager.GetString("OTPExpiredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không hợp lệ.
        ///Vui lòng nhập lại cho đúng..
        /// </summary>
        internal static string OTPInvalid {
            get {
                return ResourceManager.GetString("OTPInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập/CCCD hoặc mật khẩu không đúng!.
        /// </summary>
        internal static string PasswordUnMatched {
            get {
                return ResourceManager.GetString("PasswordUnMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại của bạn đã được đăng ký!.
        /// </summary>
        internal static string PhoneNumberAccepted {
            get {
                return ResourceManager.GetString("PhoneNumberAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại của bạn chưa được kích hoạt từ OTP.
        ///Vui lòng lấy mã OTP để kích hoạt tài khoản..
        /// </summary>
        internal static string PhoneNumberNotAccepted {
            get {
                return ResourceManager.GetString("PhoneNumberNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không tồn tại.
        ///Liên hệ với trung tâm điều hành..
        /// </summary>
        internal static string PhoneNumberNotExists {
            get {
                return ResourceManager.GetString("PhoneNumberNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND {0} đã được sử dụng ở tài khoản khác.
        ///Liên hệ Trung tâm hiến máu để được hỗ trợ..
        /// </summary>
        internal static string SystemUserCheckIdCard {
            get {
                return ResourceManager.GetString("SystemUserCheckIdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đợt lấy máu đã đủ số lượng người đăng ký.
        ///Vui lòng chọn 1 đợt lấy máu khác..
        /// </summary>
        internal static string VuotSoLuongDangKyDotLayMau {
            get {
                return ResourceManager.GetString("VuotSoLuongDangKyDotLayMau", resourceCulture);
            }
        }
    }
}
